baseURL = "https://westonross.github.io/produce-post/"
relativeURLs = true
languageCode = "en-us"
title = "The Produce Post"
publishDir = "docs"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

[params]
  js = ["js/main.js"]