baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "The Produce Post"

# Remove the disableKinds line since we want taxonomies
# disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[taxonomies]
  category = "category"

[params]
  images = ["img/og-image.jpg"]
