site_config: #Add this new section at the top
  baseURL: "/"
  languageCode: "en-us"
  title: "The Produce Post"
  taxonomies:
    category: "categories"
    tag: "tags"

backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "articles"
    label: "Articles"
    folder: "site/content/articles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - label: "Categories"
              name: "categories"
              widget: "select"
              multiple: true
              options: ["Fresh News", "Markets", "Opinion", "Recipes", "Culture"]
              default: ["Fresh News"]
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Featured Image", name: "image", widget: "image"}

      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Contact Information"
            name: "contact_entries"
            widget: "list"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
