name: Hugo build

on:
  push:
    branches:
      - master  # Already correct in your file

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build TinaCMS admin
        run: npx tinacms build

      - name: Build Hugo site
        run: hugo --minify --destination docs

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs
          git commit -m "Rebuild site" || echo "No changes to commit"
          git push